enum cardType {
  common,
  rare,
  epic,
  legendary
}

List<String> commonDTACardsList = [
  'Angelic Boots',
  'Better D II',
  'Blood Pact',
  'Bolas',
  'Bonus Blow',
  'Broken Sword',
  'Buh Bye II',
  'Codex',
  'Cursed Helm',
  'Cursed Pauldrons',
  'Dig Deeper',
  'Double Up II',
  'Elven Boots',
  'Empowered',
  'Falcon',
  'Generous',
  'Get That Outta Here II',
  'Getting Paid II',
  'Ginger Breadman',
  'Gold Digger',
  'Golden Crown',
  'Golden Rule',
  'Greed',
  'Health Potion',
  'Helping Hand II',
  'Life Funnel',
  'Magnifying Glass',
  'Meeple Mercenary',
  'Not This Time II',
  'One More Time II',
  'Pack Mule',
  'Prophetic Orb',
  'Prosperity',
  'Purge',
  'Recall Scroll',
  'Regenerating Orb',
  'Resilient Shield',
  'Samesies II',
  'Six It II',
  'Snare Trap',
  'So Wild II',
  'Strength Serum',
  'Tank',
  'Tome Of Knowledge',
  'Transference II',
  'Treasure Hunter',
  'Trench Coat',
  'Triple Up II',
  'Try Try Again II',
  'Twice As Wild II',
  'Vegas Baby II',
  'What Status Effect II'
];

List<String> rareDTACardsList = [
  'Angelic Boots II',
  'Black Belt',
  'Blood Pact II',
  'Bonus Blow II',
  'Brass Knuckles',
  'Broken Sword II',
  'Buh Bye III',
  'Campfire',
  'Cat Burglar',
  'Codex II',
  'Coin Purse',
  'Cursed Bracers',
  'Dig Deeper II',
  'Double Up III',
  'Elven Boots II',
  'Empowered II',
  'Falcon II',
  'Firstest Strike',
  'Generous II',
  'Get That Outta Here III',
  'Gingerbread Man II',
  'Gold Digger II',
  'Golden Crown II',
  'Golden Rule II',
  'Greed II',
  'Health Potion II',
  'Holy Relic',
  'Leather Armor',
  'Life Funnel II',
  'Magnifying Glass II',
  'Meeple Mercenary II',
  'Pack Mule II',
  'Prophetic Orb II',
  'Prosperity II',
  'Purge II',
  'Reboot',
  'Recall Scroll II',
  'Regenerating Orb II',
  'Salve-ation',
  'Slightly Wild',
  'Snare Trap II',
  'So Wild III',
  'Strength Serum II',
  "The Ol'Switcheroo",
  'Throwing Canes',
  'Tip It II',
  'Tome Of Knowledge II',
  'Transference III',
  'Treasure Hunter II',
  'Triple Up III',
  'Try Try Again III',
  'Unstoppable',
  'Utility Belt',
  'Vegas Baby III',
  'What Status Effects III',
  'X-Ray Specs'
];

List<String> epicDTACardsList = [
  'Angelic Boots III',
  'Better D III',
  'Blood Amulet',
  'Bolas II',
  'Buh, Bye IV',
  'Campfire II',
  'Codex III',
  'Coin Purse II',
  'Cursed Bracers II',
  'Cursed Helm II',
  'Cursed Pauldrons II',
  'Dig Deeper III',
  'Double Up IV',
  'Elven Boots III',
  'Firstest Strike II',
  'Full Mythril Jacket',
  'Generous III',
  'Getting Paid III',
  'Gingerbread Man III',
  'Golden Crown III',
  'Guard Dog',
  'Health Potion III',
  'Leather Armor II',
  'Meeple Mercenary III',
  'Not This Time III',
  'Pack Mule III',
  'Prophetic Orb III',
  'Prosperity III',
  'Purge III',
  'Reboot II',
  'Recall Scroll III',
  'Regenerating Orb III',
  'Salve-ation II',
  'Scrooged',
  'Six-It III',
  'Skadoosh',
  'Slightly Wild II',
  'Stamina Tonic',
  'Tank II',
  "The Ol'Switcheroo II",
  'Tip It III',
  'Treasure Hunter III',
  'Try, Try Again IV',
  'Twice as Wild III',
  'Unstoppable II',
  'Utility Belt II',
  'Vegas Baby IV',
  'X-Ray Specs II'
];

List<String> legendaryDTACardsList = [
  'Black Belt II',
  'Blazing Effigy',
  'Blinding Amulet',
  'Blood Pact III',
  'Brass Knuckles II',
  'Campfire III',
  'Codex IV',
  'Cookie Exchange',
  'Dig Deeper IV',
  'Electro Gauntlets',
  'Falcon III',
  'Fire Snake Immunity',
  'Full Mythril Jacket II',
  'Get That Outta Here IV',
  'Gingerbread Man IV',
  'Golden Crown IV',
  'Golden Rule III',
  'Guard Dog II',
  'Health Potion IV',
  'Holy Relic II',
  'Life Funnel III',
  'Meeple Mercenary IV',
  'Not This Time IV',
  'One More Time III',
  'Poison Syringe',
  'Prophetic Orb IV',
  'Prosperity IV',
  'Purge IV',
  'Recall Scroll IV',
  'Resilient Shield II',
  'Salve-ation III',
  'Samesies III',
  'Skadoosh II',
  'Slightly Wild III',
  'So Wild IV',
  'Stamina Tonic II',
  'Strength Serum III',
  'Throwing Canes II',
  'Tome of Knowledge III',
  'Treasure Hunter IV',
  'Triple Up IV',
  'Twice As Wild IV',
  'What Hands?'
];